### ISSUE TITLE
Feature Request: Show scroll bar on initial load

### ISSUE THREAD

**Issue by RhysyG** [utatti/perfect-scrollbar#324]
Hi there,

Just thought it would be a good UX feature to be able to have the option to make the scroll bars visible on initial load so the user knows there is scrolling content.

Thanks and great work!

**Comment by noraesae** [comment]
:+1: I think it must be really handy, but may need some work. For the time being, I don't have enough time to contribute to this plugin, so I'm not sure when to work on this. Surely, every contribution from anybody will be really welcomed!

Thanks for your interest on the plugin.

**Comment by jaimz22** [comment]
I'd like for the scrollbars to be visible on initial load as well.

**Comment by fabiobiondi** [comment]
+1

**Comment by bugfreetech** [comment]
I am considering working on this request, it should be as simple as removing a css class on initial mouse hover (to retain the fade in/out behaviour) or simply changing main scrollbar css to always visible

**Comment by bugfreetech** [comment]
I have opted to change my css so the bar is always visible. The bar now shows on initial load, as long as the element is scrolled first.
For now, a workaround:
$("element").scrollTop($("element").scrollTop()+1); $("element").scrollTop($("element").scrollTop()-1);
Works great (unless you are scrolled all the way to the bottom, it will jump up 1px).

**Comment by magnetronnie** [comment]
+1
I'm using the scrollbar on widgets that contain items in a list and it's not always clear the list is longer than what's visible.

**Comment by AlessandroFlati** [comment]
Just write your own css:

```css
.ps-scrollbar-y-rail{
	opacity: 0.6 !important;
}
```

**Comment by DanielApt** [comment]
@AlessandroFlati You can indeed do something like this, and recently we've also added custom theme support. We however have not yet had any ability to only show the scrollbar upon initialisation.

If you did want to always see the scrollbars, feel free to check out the [documentation](https://github.com/noraesae/perfect-scrollbar/blob/master/README.md).

**Comment by no1youknowz** [comment]
Just to add my 2.c to this.

I wanted the scrollbar on load of an overlay and then disappear on scroll.

I added a class which exposes it.

	.overlay-detail.oninit .ps>.ps__scrollbar-y-rail>.ps__scrollbar-y {
	    height: 314px !important;
	}

	.overlay-detail.oninit .ps>.ps__scrollbar-y-rail {
	    opacity: 1 !important;
	    display: block !important;
	}

Which when my overlay gets shown, the class gets added.

For it to disappear (as normal) when the scrollbar is moved...

	$(".overlay .overlay-detail-inner").perfectScrollbar().promise().done(function() {
		$(document).on('ps-scroll-down', function () {
			window.setTimeout(function() {
  				$(".overlay .overlay-detail").removeClass("oninit");
  			}, 750);
		});
	});

I found that 750ms was the optimal time, otherwise the bar would disappear and reappear for an instant.

@noraesae many thanks for creating this plugin.  Definitely solved an issue for me!

**Comment by utatti** [comment]
I think I'd leave it to user implementation, as it's really simple(2 lines of code).

```js
new PerfectScrollbar('#container');
setTimeout(() => $('#container').classList.add('ps--focus'), 0);
setTimeout(() => $('#container').classList.remove('ps--focus'), 750);
```

I use `ps--focus` here for simplicity, but users can define their own class.

I've added an example `show-on-initial-load.html` in the `next` branch.
