### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jeremygachet** [utatti/perfect-scrollbar#364]
Hi and thank you very much for your great work.
I use your code on big project and I have a small memory leak using it.
All dom elements added in the scrollable div are maintained.
I think that the top div created with Jquery is not destroyed with the scope.
I think the issue is near this one: 
http://rinat.io/blog/angularjs-and-jquery-plugins-memory-leaks

Thank you in advance

**Comment by denniskuligin** [comment]
Well I can agree, that there's definely some memory leak exists...

**Comment by jeremygachet** [comment]
And I don't understand why, everthings seems to be cleanup as needed in the directive, but their is still som dom nodes which are retained.

**Comment by DanielApt** [comment]
I've just been looking further in to this.

How do retained DOM nodes differ from detached ones? I namely can't find any detached DOM nodes.

**Comment by mAAdhaTTah** [comment]
FWIW, my best guess is the detached DOM nodes are getting captured in a closure scope somewhere, without diving into the code itself.

**Comment by utatti** [comment]
In the `next` branch, I took care of possible memory leaks, mainly of event listeners and element bindings. I guess now nothing's leaked if PS instance is released.

Thanks for your reports!
