### ISSUE TITLE
suppressScrollX still creates x-axis divs

### ISSUE THREAD

**Issue by mAAdhaTTah** [utatti/perfect-scrollbar#456]
Does it actually need to or can those simply not be created during initialization if we don't need to scroll along the x-axis?

**Comment by noraesae** [comment]
Sorry for the late response.

It's created by default as we choose to make `suppressScrollX` work like there's no need for the X scrollbar. I think your point is valid, but it may need some work. Any contribution will also be welcomed.

Thanks for the report!

**Comment by utatti** [comment]
Currently, suppressing and activating each axis share the same path. I think it's quite handy for styling, and thus I may stick to the current behaviour.

I'm really sorry, and thanks again for your suggestion.
