### ISSUE TITLE
The rtl examle is not working on firefox & IE 11

### ISSUE THREAD

**Issue by ettigr** [utatti/perfect-scrollbar#484]
The rtl examle is not working on firefox & IE 11

**Comment by DanielApt** [comment]
I've finally had the chance to figure out the cause of this, and still am working on the solution.

Upon initialisation, in IE 11 the default `scrollLeft` is `0`, and ranges to the negative value of the scrollable width, e.g. `-600`.

In other browsers it initialised with a `scrollLeft` of `600`, and allows scrolling to `0`.

| IE 11 & FF  | other browsers  |
|---|---|---|---|---|
| 0 to -600  | 600 to 0  |

**Comment by utatti** [comment]
Moved.
