### ISSUE TITLE
Touch propagation

### ISSUE THREAD

**Issue by MigFerreira** [utatti/perfect-scrollbar#538]
I have seen there already exists a similar issue reported and already closed, 
but i seem to be having the same problem only on Ipad.
I am using angular with perfect-scrollbar, and there is big problems in editing the fields.

[http://codepen.io/MigFerreira/pen/grvBkR?editors=1010](http://codepen.io/MigFerreira/pen/grvBkR?editors=1010)

If i request desktop site (which is exacly the same dont know what the browser does internally) it works properly.

**Comment by dietergeerts** [comment]
This is still a problem, on the ipad, when you click in the scrollable area, the touch (click) doesn't propagate.

**Comment by noraesae** [comment]
`swipePropagation` seems like not working. Will investigate.

**Comment by lechup** [comment]
I'm having similar issue. I'm using:
* https://github.com/callemall/material-ui
* https://github.com/zilverline/react-tap-event-plugin

PS is not propagating touchStart event to MaterialUI, I'm testing this change:
https://github.com/lechup/perfect-scrollbar/commit/e8e967118df786343282a4c4180bef40bb33ab5c

With success. But probabbly it destroy some default behaviour?

@noraesae why we would want to stop propagating touchStart events by default?

**Comment by mptardy** [comment]
+1

**Comment by iegorov** [comment]
Try to use `handlers: ['click-rail', 'drag-scrollbar', 'keyboard', 'wheel']` prop without 'touch' in initialize.

**Comment by OxLeon** [comment]
+1 :(

**Comment by elephantme** [comment]
+1

**Comment by sconix** [comment]
This is also issue in the ngx-perfect-scrollbar wrapper library which I went around by generating the touch event and sending it to the parent. It works but is a bit hackish so would be nice to be able to get rid of that.

**Comment by sconix** [comment]
Would be nice to get this fixed. @utatti do you know why the touchStart event propagation is stopped in the touch handler? If I knew the reason I could try to think of a solution.

**Comment by utatti** [comment]
I've fixed this in the master. It'll be released as a new version later, but you can always test it by manually building from source.

I've removed `swipePropagation` option itself, because it's `true` by default and it's exactly how native scroll works. Also touch propagation cannot be implemented without dropping the option. Now all touch events will be properly propagated.

If there is a new problem by this fix, please upload a separate issue. Thanks.

**Comment by Bhuvan-Arora** [comment]
I am using nested perfectscrollbars on the same page.
Parent div is scrolling vertically and child div is scrolling horizontally.

But in ios devices by touching the child div I am unable to scroll the vertical scrollable parent. It is working fine for all other devices but not in ios devices.

PS : I am using latest version of perfect scrollbar.

Any Solution will be appreciable @utatti 👍

**Comment by domipange** [comment]
I was also having problems with touch scrolling using nested scroll bars. 

So I tried to fix this by altering first few lines of code in perfect-scrollbar.css and it seems to work quite nicely on Chrome v96.0.4664.110, Windows 10 v21H2, Lenovo X1 Yoga Laptop (touch screen).

`/* Hide scrollbar for Chrome, Safari and Opera */
.ps::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.ps {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

/*
 * Container style
 */
.ps {
  overflow: auto !important;
  overflow-anchor: none;
  -ms-overflow-style: none;
  touch-action: auto;
  -ms-touch-action: auto;
  overscroll-behavior: contain !important;
}`
