### ISSUE TITLE
Problem with inside scroll elements in FF and IE

### ISSUE THREAD

**Issue by jakkor** [utatti/perfect-scrollbar#571]
After adding select tag to the container with perfect scrollbar scrolling the select tag content does not work correctly.
It is scrolling the whole container instead of just the select tag content.

This issue is in Firefox only I think. I tested it on 49.0. Chrome is working fine.

https://jsfiddle.net/jakkor/4t85xw9L/

**Comment by noraesae** [comment]
It was known bug for Firefox: #247 #311 
However, it was resolved in the newest version of Firefox. I've just tested it and it works just fine in my env(Firefox 49.0 macOS). It could be OS specific problem. Can you specify your env?

If you need a quick work around, please revert the following change. It's the commit which removed the workaround.

https://github.com/noraesae/perfect-scrollbar/commit/eb02d5ae65ea6d9ea41ab149980f375c78efcebc

**Comment by robobalasko** [comment]
In FF 52 on Mac OS this still does not work.

**Comment by pitaya921** [comment]
In FF 53.0.3 (32) on Windows this still does not work

**Comment by utatti** [comment]
I reverted the removal of workaround. I also added info to Caveats.
