### ISSUE TITLE
Forcing propagation of wheel event to children

### ISSUE THREAD

**Issue by svk31** [utatti/perfect-scrollbar#577]
I ran into an issue with D3 and trying to capture a mouse wheel event to zoom on a chart where the event is not propagated properly. Using ps-child class is not enough, as the scrollTop logic returns false since the underlying child does not actually have any scrollable content.

My simple solution was to add an additional class that allows you to force consumption of the event by the child element:

`mouse-wheel.js -> shouldBeConsumedByChild`

```
if (child.className.match(/ps-must-propagate/)) {
    // force consumption by child
    return true;
}
```

Would you include this if I make a PR for it?

**Comment by prog8** [comment]
This is indeed serious problem in perfect-scroller. Not only charts are a problem here.

**Comment by utatti** [comment]
It's fixed in the `next` branch, with `ps__child` and `ps__child--consume`.

- https://github.com/utatti/perfect-scrollbar/blob/next/src/handlers/mouse-wheel.js#L6
- https://github.com/utatti/perfect-scrollbar/wiki/FAQ#scrolling-children-inside-perfect-scrollbar

Thanks for the report!
