### ISSUE TITLE
ps event bubbles to parent ps

### ISSUE THREAD

**Issue by avkvak** [utatti/perfect-scrollbar#581]
https://jsfiddle.net/gbfLazpx/335/

Dont understand why .child reaching-end event bubbles to the parent, and my function fires? How can I fix it and call this function when just parent scrollbar reaches end?

If I add event.stopPropogation() to this function, its newer runs.

**Comment by MennoVS** [comment]
In your handler you can do a (event.srcElement === elementToWatch) comparison before acting on the event

**Comment by utatti** [comment]
Sorry, it's been (really) a while! Fixed in 087964e1451d9c3ad763d9ba340dd00d9a0a04d6.
