### ISSUE TITLE
Nested ps-container error

### ISSUE THREAD

**Issue by Josbert-Lonnee** [utatti/perfect-scrollbar#588]
Context: When the mouse wheel is used over a 'ps-container' element, but the mouse is over a sub-element with the 'ps-child' or 'ps-container' class, AND that child element has some space to scroll, then the event is not handled, making it end-up at that element. That is OK.

Bug: But when a 'ps-child' has room to scroll and is inside a 'ps-container' that has no room to scroll, which is again in a 'ps-container' the event is handled and the 'ps-child' is not scrolled.

Fix: In function 'shouldBeConsumedByChild' not only the first 'ps-child' or 'ps-container' should get checked, but all children. The event should not get handled when any child is found. With other words: 'querySelectorAll' should there get used instead of 'querySelector'.

**Comment by utatti** [comment]
`ps-container` is no more used and also shouldn't be nested. Please use `.ps__child` instead.
