### ISSUE TITLE
Rough jump of content position if content size is changed dynamically

### ISSUE THREAD

**Issue by ivankrylatskoe** [utatti/perfect-scrollbar#593]
Hi. Consider the following situation.
1) You begin scrolling content down (mouse down event).
2) a) When you are close to the bottom, script dynamically inserts more content in the bottom of the container. Content height is increased (i.e. by 2000px) .
b) Script calls perfectScrollbar('update'). Scrollbar thumb position and size are changed. 
3) You continue scrolling content down without releasing mouse. 
And here we have NEGATIVE EFFECT: scroll position jumps roughly from previous position to the new position according to current scrollbar percentage.

For example. 
ScrollTop can be changed between 0 and 1000 pixels.
User starts increasing scrollTop slowly (scrolls content down).

At 80% of max ScrollTop the content was dynamically loaded (i.e the height was increased by 2000px so that maxScrollTop becomes 3000px).
Before content load. ScrollTop = 80% * 1000 = 800px.
After content load. Suppose that user scrolled scrollbar 1% down. So we get ScrollTop = 81% * (1000 + 2000) = 2430px.

So the scrollTop position jumped from 800 to 2430px at once.

NOTE: standard scrollbar does not have this negative effect.

To try this issue, check this JSFiddle:
https://jsfiddle.net/ivankrylatskoe/q8f14nxm/4/

Run it and scroll scrollbar down. You will notice theese jumps.

You can comment perfectScrollbar() line to use ordinary scrollbars. You will see that this negative effect disappears.

**Comment by noraesae** [comment]
I confirmed the problem. I recently do not have enough time to contribute to perfect-scrollbar, and may take quite a while for me to fix this. This issue is related with the following file.

https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/drag-scrollbar.js

I hope I can see a PR concerning this. I will surely try to fix if I become idle, which I cannot be sure when.

**Comment by utatti** [comment]
I will work on this.
