### ISSUE TITLE
Scroll-linked warning on firefox

### ISSUE THREAD

**Issue by fabio-ravizzotti** [utatti/perfect-scrollbar#598]
I want to inform that on firefox 50.1.0 appears the following warning message:
"this site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!"

I've no problems, but this may cause problems in some situations?

Thanks.

**Comment by noraesae** [comment]
It is a warning, so may not become an instant problem. However, it is definitely worth looking into it. Thanks for your report.

**Comment by utatti** [comment]
I added this to [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats) for the time being, as it's kind of inevitable in the current code base. Nonetheless, any kind of contribution will be welcomed. Please feel free to suggest a solution or upload a pull request.
