### ISSUE TITLE
Chrome 56 Scroll Anchoring breaks scrolling

### ISSUE THREAD

**Issue by sheldonlynn** [utatti/perfect-scrollbar#612]
Scroll anchoring, now turned on by default in Chrome 56, causes massive issues with perfect-scrollbar.

To fix this, add CSS attribute "overflow-anchor: none;" to scrolling container.

Reference: https://github.com/WICG/ScrollAnchoring/blob/master/explainer.md

**Comment by morrisjn** [comment]
Are there any plans to support this feature?

**Comment by utatti** [comment]
It may be tricky to implement this feature with JS. I may go with adding `overflow-anchor: none;` by default. Thanks for your report!
