### ISSUE TITLE
Visualization problem with Chrome into bootstrap 3 panel

### ISSUE THREAD

**Issue by fabio-ravizzotti** [utatti/perfect-scrollbar#613]
Hi,
I've a visualization problem with perfect scrollbar used into a bootstrap 3 panel only with Chrome (tested in version 56 and older).

All details here http://stackoverflow.com/questions/42009781/perfect-scrollbar-not-rendered-well-on-chrome.

Someone can explain me why it happens?

Thanks.

Make sure these boxes are checked before submitting your issue -- thank you!

- [X] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [X] Search if there's already one reported in Issues
- [X] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [X] Provide a page or source code where the issue can be checked

**Comment by utatti** [comment]
Sorry for the late response. Can I have a detailed page or snippet to look into? It is difficult for us to investigate the issue without 3rd-party library prepared already.

**Comment by utatti** [comment]
Closed for the inactivity.
