### ISSUE TITLE
Page scroll when clicking different tabs in perfect-scrollbar.js horizontal tab

### ISSUE THREAD

**Issue by Dang007** [utatti/perfect-scrollbar#614]
_I am trying to move the scroll tab position when clicking tab but to no avail. Only scroll-er is moving below but no tab position. Method i used is below._

`cls = document.getElementsByClassName("ps-scrollbar-x-rail");
            cls1 = document.getElementsByClassName("ps-scrollbar-x");
            cls2 = document.getElementsByClassName("ps-scrollbar-y-rail");`
       
            var allClasses = document.querySelectorAll('ps-scrollbar-x-rail, ps-scrollbar-y-rail, ps-scrollbar-x');
            Array.from( allClasses ).forEach(el => el.removeAttribute('style'))               
            cls[0].setAttribute("style","width: 600px; left: 258px; bottom: 1px;"); 
            cls1[0].setAttribute("style","left: 143px; width: 333px;");
            cls2[0].setAttribute("style","top: 0px; right: -255px;");
            $("#Default").removeClass( "contentHolder ps-container ps-theme-default ps-active-x" ).addClass( "contentHolder ps-container ps-theme-default ps-active-x ps-in-scrolling ps-x" );`

_Tried this method to move scroll-er position but its seems to work to remove add style but not move the scroll-er to the position as i mentioned and change the class by id="default" in the div which is shown below._

`<div id="Default" class="contentHolder">
    <div class="content cd-tabs-navigation">
         <ul>
             <li><a data-content="HousingVitals" id="HousingVitals1" onclick="scrollDefault(1);" href="#0">Housing Vitals</a></li>
             <li><a data-content="Score" id="Score1" class="selected" onclick="scrollDefault(2);" href="#0">Rating Snapshot</a></li>
             <li><a data-content="locality" id="locality1" onclick="scrollDefault(3);" href="#0">Housing v/s Locality</a></li>
             <li><a data-content="Indicators" id="Indicators1" onclick="scrollDefault(4);" href="#0">Top Indicators</a></li>
             <li><a data-content="Compare" id="Compare1" onclick="initialize();" href="#0">Nearby Housings</a></li>  @*onclick="scrollUpMenu('near')"*@
              <li><a id="liInsights" data-content="Insights" onclick="scrollDefault(6);" href="#0">Key Insights</a></li>
              <li><a id="liDetailscore" data-content="Detailscore" onclick="scrollDefault(7);" href="#0">Detailed Rating</a></li>
                                    <li><a data-content="Wisometer" id="Wisometer1" onclick="scrollDefault(8);" href="#0">Wiso Meter</a></li>
                                </ul>                                    
                            </div>
                        </div>`

i am using perfect-scrollbar.js and perfect-scrollbar.css

_I have uploaded image to show the issue i got. Third image is where i used the method to change the position of the tab with scroll-er_
![scroller](https://cloud.githubusercontent.com/assets/25549020/22618673/c2dcd8a6-eb08-11e6-9abd-ab162da94209.jpg)

**Comment by utatti** [comment]
You are setting `left` and `top` position, not the `scrollLeft` and `scrollTop`. PS doesn't use `left` or `top` styles. To update the position, updating `scrollLeft` and `scrollTop` is enough. Also, class names shouldn't be removed for PS to properly work.
