### ISSUE TITLE
reduce unnecessary nesting of css selectors

### ISSUE THREAD

**Issue by loominade** [utatti/perfect-scrollbar#615]
currently there are a many selectors like:

```css
.ps > .ps__scrollbar-x-rail > .ps__scrollbar-x {
  …
}
```

and I was wondering why. couldn't the same be achieved with

```css
.ps__scrollbar-x {
  …
}
```

the name is unique enough and `.ps__scrollbar-x` will never appear outside of this context, right?

**Comment by utatti** [comment]
Hmm, I think it's a valid point. Will fix this.
