### ISSUE TITLE
Does not bind to new dom elements + jFiddle + solution

### ISSUE THREAD

**Issue by DazWilliams** [utatti/perfect-scrollbar#616]
Created jFiddle to demonstrate: https://jsfiddle.net/1qr5av5g/

Possible solution: http://stackoverflow.com/questions/10920355/attaching-click-event-to-a-jquery-object-not-yet-added-to-the-dom

$(document).on();

$(document).on({
    click: function () {},
    mouseover: function () {},
    mouseout: function () {}
}, '#element_id');

**Comment by utatti** [comment]
There is no function in JS to automatically bind something in new objects. Your example on events is not binding them, but it's just a technic called event delegation.

To bind new PS, you can simplify call again after it is added.

```js
var $newDiv = $("<div>", {id: "foo", "class" : "container"});
$newDiv.appendTo(somewhere);
$newDiv.perfectScrollbar();
```

Please beware that jQuery support will be dropped in the next release.

Thanks.
