### ISSUE TITLE
cooperation with bootstrap scrollspy

### ISSUE THREAD

**Issue by ktsaou** [utatti/perfect-scrollbar#617]
Hi,

thank you for perfect-scrollbar. A lot easier and better compared to anything I tried so far.

I use it in [netdata](https://my-netdata.io).

I have a little problem with it and I was looking for some help/directions. In netdata we have the main menu of charts like this:

![image](https://cloud.githubusercontent.com/assets/2662304/22858464/ecbe7292-f0c6-11e6-9241-ffdae28e9b7d.png)

You can see it live at https://london.my-netdata.io/

The problem I have, is that if you place your mouse over the menu (bootstrap scrollspy  on the right of the screen) and start scrolling the page with your mouse wheel, the menu is expanding and shrinking to follow the menu and submenu that corresponds to the view.

Everything is good so far, but if you keep scrolling, at about the middle of the page, perfect-scrollbar will leave a large blank area below the menu, while the top half of the menu will be cropped at the top, like this:

![image](https://cloud.githubusercontent.com/assets/2662304/22858459/df292582-f0c6-11e6-9999-b7e4705f79ff.png)

In a few cases (mainly laptops), I have seen perfect scrollbar slowly animating the menu, trying to eliminate the blank area below the menu (it is strange I know - but I guess it is just re-calculating something and this leads to this animation).

If I remove perfect scrollbar and leave the native browser scrollbar, the menu is never cropped at the top leaving a blank area below it. It is cropped at the top, only when it does not fit in the view.

I would appreciate a few directions on how to solve this.

Thank you and keep up the good work!

**Comment by utatti** [comment]
Hello, thanks for your report.

Can I have more information concerning initialization, preferably a code snippet? Setting `wheelPropagation: false` and `scrollYMarginOffset: 5` may help, but I'm not sure without looking into code.
