### ISSUE TITLE
Horizontal Scrolling not working (showing only on developer tools)

### ISSUE THREAD

**Issue by IrvingArmenta** [utatti/perfect-scrollbar#624]
My issue is that the scroll on x is not working, I'm using the plugin in conjunction with the "floatThead" plugin, not sure if you know this plugin, I only want the element ".operations__table" to scroll on x and y, right now as it is, it only scrolls on Y and you can see the custom scroll on the right, what I'm aiming to do is to also hace a custom scroll on X, but is not showing at all, I'm using min-width to stablish at what point the X scrollbar should appear ( 870px ) 

Here is the jsfiddle: https://jsfiddle.net/qyrztt4L/4/

the scrollbar on x is visible as an element on the developer tools, but is not visible at all, only ".operations__table" should have both scroll on X and Y, not the whole ".operations" div.

I'm using all latest versions as you might see on external resources of the jsfiddle, and I'm using latest Chrome on windows 7.

**Comment by IrvingArmenta** [comment]
I want to achieve exactly what this plugin does:

http://plugins.gravitysign.com/rollbar/

if you resize the browser windows, the whole scrollbar works for the site.

**Comment by utatti** [comment]
To activate scroll X, it should have specified width where content can be overflowed. Currently the container has `min-width`, but no `max-width` or `width`. Currently the width is just full-content width and surely scroll will not work. It's not an issue of PS, and you can see it with commenting out PS part.
