### ISSUE TITLE
Horizontal scroll with mouse wheel

### ISSUE THREAD

**Issue by ldetomi** [utatti/perfect-scrollbar#631]
Hi,
I use perfect-scrollbar to horizontally scroll my containers (I also forced disable of vertical scrolling using `suppressScrollY:true` option).

Is there a a way to **enable mouse wheel to horizontally scroll** these kind of boxes, so change default behaviour?

**Comment by utatti** [comment]
You can do it with the following option:

```js
{
  suppressScrollY: true,
  useBothWheelAxes: true,
}
```
