### ISSUE TITLE
Scroll bar is not displayed on mobile

### ISSUE THREAD

**Issue by valecarlos** [utatti/perfect-scrollbar#633]
I've noticed that when on mobile, the scrollbar is not displayed, mainly because it relies on the :hover status to show it, and since on mobile there is no hover status it's never shown although it´s functionality is working well behind the scenes. This issue can be seen on the landing page http://noraesae.github.io/perfect-scrollbar/ from there going to devtools and toggling the device toolbar, i have not seen any documentation related to mobile devices, so i'm not sure if it's supposed to be this way.

**Comment by utatti** [comment]
Thanks for your report. This issue should be addressed. I think adding `ps--scrolling-x`/`ps--scrolling-y` on touch scrolling will be the easiest fix for this. I will work on this in a while, but anybody can jump in whenever before `status:ongoing` is added.

**Comment by utatti** [comment]
Will do this.

**Comment by utatti** [comment]
Actually I've noticed that scrollbars are actually displayed, as there *is* hover event in mobile too. It's fired on touches, so it works kinda like `focus` and `blur`. But anyway I guess there can be some devices not supporting this, so will add the `scrolling` class anyway.

**Comment by utatti** [comment]
Fixed.

**Comment by valecarlos** [comment]
Thanks! sorry i wasn't quicker to answer

**Comment by prajapati11sandeep** [comment]
try this
.ps-container>.ps-scrollbar-x-rail, 
.ps-container>.ps-scrollbar-y-rail {
  opacity: 1;
}

**Comment by speeday** [comment]
It worked for me in following way to show it initially while rendering the view but it will have the height automatically once we scroll it, Hope it would be helpful to you.

.ps:not(.ps--active-y) .ps__thumb-y {
	height: 100px !important; /* It is based of my structure you can change it according to your structure */
}

.ps:not(.ps--active-y) .ps__rail-y {
	background-color: #dcdcdc;
    width: 6px;
    height: 100% !important;
    display: block !important;
}
