### ISSUE TITLE
The new look and behavior of scrollbar is not that good

### ISSUE THREAD

**Issue by medBouzid** [utatti/perfect-scrollbar#634]
I was using a previous version of perfect-scrollbar and today I downloaded the latest version, however it seems that the scrollbar get thiner and when I hover the mouse over it it becomes larger, I am posting this to request this to be a secondary effect that can be added as option (I think it's better), and the second thing I would like to know how I can get the old look and behavior while using the current version  ?  Thanks

**Comment by itsOgden** [comment]
@medBouzid it does seem like having this as an option would be good, but for me, I just override the css so it always does what I want (which is staying a static size and always visible);

```
.ps-container{
    div{
        border-radius: 0 !important;
    }
    .ps-scrollbar-y-rail, .ps-scrollbar-x-rail{
        opacity: 1 !important;
    }
    .ps-scrollbar-y-rail, .ps-scrollbar-y-rail .ps-scrollbar-y{
        right: 0 !important;
        width: 0.5rem !important;
    }
    .ps-scrollbar-x-rail, .ps-scrollbar-x-rail .ps-scrollbar-x{
        bottom: 0 !important;
        height: 0.5rem !important;
    }
}
```

**Comment by medBouzid** [comment]
@itsOgden Thank you for the answer and the snippet of code :) I was using the previous version.. so I didn't changed the old css file, I just changed the JavaScript file to "upgrade", now I run the latest version of perfect-scrollbar with the old css, your solution is good as well, thanks

**Comment by utatti** [comment]
I'm really sorry that the new design is not good for you, I just wanted it to look like ones in iOS. However, now the style is in [a plain CSS](https://github.com/utatti/perfect-scrollbar/blob/next/css/perfect-scrollbar.css) and it's much easier to play around it!

Sorry again, and thanks for your opinion.
