### ISSUE TITLE
does not work Firefox and Edge while working perfect on Chrome

### ISSUE THREAD

**Issue by brknblgc** [utatti/perfect-scrollbar#636]
It does not works on firefox and edge. and i dont know anything about it. Its same codes, my website on my local server. Works great on Chrome but does not work with Firefox or Edge.

**Comment by cfatorNSS** [comment]
+1

**Comment by adil-gikian** [comment]
+1

**Comment by Abdipour** [comment]
+1

**Comment by minamoto19** [comment]
+1

**Comment by minamoto19** [comment]
I'm having the same problem.
It works correctly in Chrome, Opera, Safari and IE11 but not working in Firefox and Edge.

From the developer tools I noticed that in Firefox and Edge the "ps--active-y" class was missing from my container.
Tried to add it manually. After scroll was removed.

I'll try too dig deeper.

**Comment by minamoto19** [comment]
Hi again.

Try to define a height property to the container you want to be scrollable.

That fixed the issue for me.

**Comment by utatti** [comment]
`height` should be set for scroll container. It's the same for browser native scroll with `overflow: auto`. Also, in @minamoto19's case, `overflow: hidden` is not set for scroll container, but for body. For the detailed usage, please refer to README.

If there are other issues, please provide some code snippets.

p.s. Please do not spam '+1' with comments. Emoji reaction is recommended by GitHub.

**Comment by mikeluyties** [comment]
Unfortunately, this issue still occurs if you are using a height with calc() =/

**Comment by tsujihidetaka** [comment]
Same as above.

**Comment by tsujihidetaka** [comment]
+1

**Comment by lamtrc** [comment]
was not a big fan of chrome, but unfortunately, stuff like this forces me to use chrome because it works while firefox and edge fails.  you shouldn't have to set a fixed px "height" in order for overflow-y: scroll to work because if you resize your browser window, it won't proportionally scale.  try to use % for height in chrome, and when you shrink your browser window, the div will shrink with it, and the scroll bar works perfectly fine.

**Comment by tiago0022** [comment]
I solved the problem by removing the `flex-direction: column-reverse;` from the scrollbar container
