### ISSUE TITLE
Experiencing laggy performance in 0.6.16 after upgrading from 0.6.10

### ISSUE THREAD

**Issue by dawid84** [utatti/perfect-scrollbar#637]
I am wondering what might have been updated from 0.6.10 to 0.6.16 that could be the cause of very visibly worse performance we are experiencing in our app on complex/lengthy pages. Any assistance would be greatly appreciated.

**Comment by utatti** [comment]
There had been a quite list of changes and I cannot figure out which change caused the issue. Now large part of PS has been being rewritten and the new 1.0 release is coming soon. Please let me know if there is any issue on new releases.

Thanks again for your report.
