### ISSUE TITLE
Issue on Edge with perfect scrollbar

### ISSUE THREAD

**Issue by Steve-Mc** [utatti/perfect-scrollbar#638]
When using perfect-scrollbar in a textarea on Edge, after the textarea has been filled with text and then deleted the textarea's caret is positioned in the scrollbar and all text is placed within the text area.

JSFiddle: https://jsfiddle.net/gbfLazpx/594/

GIF:
![edge issue](https://cloud.githubusercontent.com/assets/14161690/24245587/6e00c90a-0fbb-11e7-965c-c05c1cb40985.gif)

Does anyone have any ideas on how to deal with this issue?

**Comment by utatti** [comment]
There is known issue in textarea, which is basically because textarea is not a plain container element. I've added the info in [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats).

I'm sorry for your inconvenience, but please consider using browser native scroll for textarea.
