### ISSUE TITLE
Ps not working with disqus

### ISSUE THREAD

**Issue by keevitaja** [utatti/perfect-scrollbar#640]
Hello!

When mouse pointer is over the disqus feed, the wheel scrolling is not working. 

Example:

https://keevitaja.com/posts/multilingual-laravel-applications-the-right-way

Any way to fix this?

EDIT: i removed the perfect scrollbar from the site. But i would still like to solve it!

**Comment by utatti** [comment]
The only reasons I can come up with are:

1. Disqus feed is out of scroll container. In this case, mousewheel event itself isn't fired.
2. Disqus feed is in the container, but absorbing the events. In this case, mousewheel event is stopped from bubbling into the container, maybe with `stopPropagation()`.

Now it seems suggestions above cannot be proven in the site, but please feel free to test them out and let me know about it :)

**Comment by keevitaja** [comment]
huh, it has been a while. but i kinda think it rather was the problem nr 2. 

I'll come back to it when similar situation represents itself. 

tnx!

**Comment by w3lifer** [comment]
@utatti, https://fiddle.jshell.net/bgjm9mpx
