### ISSUE TITLE
Wrong flag "supportsIePointer" on Chrome

### ISSUE THREAD

**Issue by rocodesign** [utatti/perfect-scrollbar#641]
https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/lib/helper.js#L82

In chrome the flag is true
console.log(window.navigator.msMaxTouchPoints)
//undefined
console.log(window.navigator.msMaxTouchPoints !== null)
//true

**Comment by utatti** [comment]
Fixed in `a81208a2ea72b4d903d852d1aecc40252a42c5b0`. Thanks!
