### ISSUE TITLE
Scrollbar behaviour appears 'laggy' on iOS 10.3.1

### ISSUE THREAD

**Issue by aaronferris** [utatti/perfect-scrollbar#644]
Hi,

Noticing some behavioural issues with the plugin after updating to iOS 10.3.1 - device is an iPhone 6.

When scrolling an element, the content scrolls at a normal speed but the scrollbar appears to lag behind for a second or so, then moves into the correct position.

This behaviour can be seen from the demo on https://noraesae.github.io/perfect-scrollbar/

I didn't notice this on iOS before 10.3.1, but cannot be sure when this was introduced as far as mobile Safari is considered. Previous iOS version was 10.1 (no behavioural issues).

Update: To add to this, it also affects desktop Safari. I'm using Safari ver 10.1.

Thanks

**Comment by aaronferris** [comment]
I've been looking into this, I believe i've whittled it down to not being the jQuery but the CSS.

In particular the css transitions in:

.ps-container > .ps-scrollbar-y-rail > .ps-scrollbar-y {
    position: absolute;
    background-color: #aaa;
    -webkit-border-radius: 6px;
    -moz-border-radius: 6px;
    border-radius: 6px;
    -webkit-transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, -webkit-border-radius .2s ease-in-out;
    transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, -webkit-border-radius .2s ease-in-out;
    -o-transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, border-radius .2s ease-in-out;
    -moz-transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, border-radius .2s ease-in-out, -moz-border-radius .2s ease-in-out;
    transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, border-radius .2s ease-in-out;
    transition: background-color .2s linear, height .2s linear, width .2s ease-in-out, border-radius .2s ease-in-out, -webkit-border-radius .2s ease-in-out, -moz-border-radius .2s ease-in-out;
    right: 2px;
    width: 6px
}

**Comment by aaronferris** [comment]
I've fixed this in my implementation by removing the transitions in my stylesheet, i'm yet to see any issues caused by doing so.

> body .ps-container > .ps-scrollbar-y-rail  .ps-scrollbar-y {
  transition: none;
}

**Comment by utatti** [comment]
There was `transition` style issue in the built result of SCSS. It could be reproduced in macOS Safari too. Now the styles has been rewritten in plain CSS and it seems like the issue has gone.

- https://github.com/utatti/perfect-scrollbar/blob/next/css/perfect-scrollbar.css

Thanks again for your report.

**Comment by aaronferris** [comment]
Thanks @utatti
