### ISSUE TITLE
Version for Magento

### ISSUE THREAD

**Issue by JoelBout** [utatti/perfect-scrollbar#648]
Hello Hyunje/everyone,

I would like to know if there is a way to make it compatible with Magento CE (my version 1.9.2.3),
I tried to upload directly CSS file in the relevant repository and same for Jquery files but as expected it was not working. Therefore maybe do you have an idea how I should proceed to have a version workable on Magento CE 1?

Thanks for your responses,

Joel.

**Comment by TonySma** [comment]
Hi!
Yes you can use it in Magento. 
Upload the files and update your layout for include the library in your theme, then clean cache and it will work. 

Tony

**Comment by JoelBout** [comment]
Hello Tony,

Thank you for your response but saying that I need to update my layout does not help much...
Maybe can you let me know in which directory should I upload those files (js and directory) on Magento?
And for the layout do you mean that for each page layout I need to include those library? Can you give me an example?

Thanks & regards,

Joel

**Comment by utatti** [comment]
I do not have experience with Magento, but the question seems like one of Magento itself, but none of perfect-scrollbar. I found a Magento documentation about custom script here:

- http://devdocs.magento.com/guides/v2.1/javascript-dev-guide/javascript/custom_js.html

You may also be able to find docs for custom CSS and user scripts too. If there is anything unclear in using Magento, please contact Magento about it.

I'm sorry that I cannot help much about it.

Thanks,
