### ISSUE TITLE
scrolling follow mouse on macos

### ISSUE THREAD

**Issue by devildant** [utatti/perfect-scrollbar#653]
Hello,
I encountered a problem with perfect scrollbar on chrome OSX.
The scroll starts when I move the mouse.
When I down the mouse the scroll up... could you help me ?

best regards

**Comment by devildant** [comment]
[IMG_3269.zip](https://github.com/noraesae/perfect-scrollbar/files/1036519/IMG_3269.zip)

**Comment by devildant** [comment]
this video show the problem, during this test i just move a mouse

**Comment by utatti** [comment]
I'm sorry for the late response here. Unfortunately it has not been reproducible in my env(macOS Chrome).

Can you specify more about reproduction, such as reproduction step, browser version, and scroll device(e.g. trackpad, bluetooth mouse, etc)?

**Comment by devildant** [comment]
hello,

I tried to reproduce the problem but it seems to have disappeared.

you can close this bug,
thx for your reply
