### ISSUE TITLE
Material dialog- prefect scrollbar not working inside md-dialog on Firefox.

### ISSUE THREAD

**Issue by pushkar1701** [utatti/perfect-scrollbar#655]
I am using angular material dialog box using 'md-dialog'. The content inside my div is not scrollable on Firefox but it works perfectly on Chrome. On the home page, it is written that PS may not work well in body, text-area, iframe or flexbox. Kindly confirm if this is related and If it is fixed? Any kind of help is appreciated.
 
- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues - https://github.com/noraesae/perfect-scrollbar/issues/636(I believe this must be related)
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by utatti** [comment]
As mentioned in the original issue, can you try setting `height` properly in the container div? If it does not work, please provide a fiddle to reproduce the problem. It's really hard to investigate on it without any working example or code.
