### ISSUE TITLE
Scrollbar height('ps__scrollbar-y') does'nt change automatically when I route to another module.

### ISSUE THREAD

**Issue by pirahana** [utatti/perfect-scrollbar#658]
Hi, 

I am using angular2-perfect-scrollbar .

Scrollbar height('ps__scrollbar-y') does'nt change automatically when I route to another module.
When the page loads for the first time, the scrollbar height is perfect, but when I route another module into this div that contains the scroller, the height does'nt change automatically. However once I just click or touch the scrollbar, it computes the height correctly. Is there a way to automatically call the update method. Also could you tell me how does the height of the scrollbar gets computed.

Could anyone  possibly tell me what am I missing here. I have used perfect scrollbar as a directive.

**Comment by utatti** [comment]
I have no experience with Angular and in fact angular2-perfect-scrollbar is not maintained by us. All I can suggest is that scrollbar geometry should be updated manually with `Ps.update(element)` or `$(element).perfectScrollbar('update')` after route update.

- https://github.com/utatti/perfect-scrollbar/tree/master#how-to-use

If you have further question about angular2-perfect-scrollbar, please refer to its own repository.

Thanks and sorry that I cannot help much here.
