### ISSUE TITLE
Home, End, Page Up, Page Down, and Spacebar Do Not Behave Correctly

### ISSUE THREAD

**Issue by conover** [utatti/perfect-scrollbar#659]
The behavior can be demonstrated on the infinite scroll example (examples/infinite-scroll.html). 

After loading additional elements:

#### Press Home Button

Expected behavior: Go to the top of the page
Current behavior: Scroll up the amount of `containerHeight`

#### Press End Button

Expected behavior: Go to the bottom of the page
Current behavior: Scroll down the amount of `containerHeight`

#### Page Up or Shit+Spacebar

Expected behavior: Scroll up a webpage, a screen at a time
Current behavior: Scroll up `90`

#### Page Down or Spacebar

Expected behavior: Scroll down a webpage, a screen at a time
Current behavior: Scroll down `90`

Reference for the proper button behavior: https://support.google.com/chrome/answer/157179?hl=en

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by ucjonathan** [comment]
I agree that the page up/down should be equivalent to the height of the container being scrolled instead of just 90 pixels.

**Comment by tkorsa** [comment]
Based on the reference @conover linked it should be the following.

[/src/handlers/keyboard.js#L111](https://github.com/utatti/perfect-scrollbar/blob/7c926ccda827dbb7d91b5b3f2a1422e325330083/src/handlers/keyboard.js#L111)
```javascript
...
case 33: // page up
  deltaY = i.containerHeight;
  break;
case 32: // space bar
  if (e.shiftKey) {
    deltaY = i.containerHeight;
  } else {
    deltaY = -i.containerHeight;
  }
  break;
case 34: // page down
  deltaY = -i.containerHeight;
  break;
case 35: // end
  deltaY = -i.contentHeight;
  break;
case 36: // home
  deltaY = element.scrollTop;
  break;
...
```
