### ISSUE TITLE
Horizontal scroll with mouse wheel with shift key

### ISSUE THREAD

**Issue by renatorib** [utatti/perfect-scrollbar#661]
Native scroll (at least on mac, idk windows/etc) allow you to hold shift key with mouse wheel to scroll horizontally. 

PS: this is a similar, but not equal as https://github.com/noraesae/perfect-scrollbar/issues/631

**Comment by MA-Maddin** [comment]
Seems to be an mac-only issue. Working on windows.

**Comment by CKGrafico** [comment]
Working on my demos on Windows

**Comment by noraesae** [comment]
It works in my mac on demo. Can you specify the env?

**Comment by utatti** [comment]
It seems like working well in the `next` branch too. Will close this.
