### ISSUE TITLE
Doesn't work theme in examples v0.8.0 (and v0.7.0)

### ISSUE THREAD

**Issue by fukusyo** [utatti/perfect-scrollbar#680]
I open `examples/custom-theme.html` and tried to click the custom button, but it doesn't work.
I changed `.ps-theme-square` to `.ps--theme_square` in `examples/custom.css`, The custom button worked!
It may show usage is wrong and not a bug.
If so, `README.md` too.

**Comment by utatti** [comment]
Hello,

Thank you very much for your report. Unfortunately theme itself will be dropped in the next version. (You can see it has been dropped in the `next` branch) Instead, a simpler CSS will be provided to be modified easily.

Thanks again.
