### ISSUE TITLE
Add setting for additional selectors for shouldBeConsumedByChild querySelector

### ISSUE THREAD

**Issue by ericdepotter** [utatti/perfect-scrollbar#681]
It is not always straightforward to add the `.ps-child` class to all elements you want to be scrollable in a ps-container. In order to prevent to have to add the` .ps-child` class I suggest to add a setting where a user can provide additional selectors to be used in the `shouldBeConsumedByChild` function.

Do you think this would be a good idea?

**Comment by utatti** [comment]
I've once thought it would be expensive to check, but actually it seems it isn't. Rather than adding an option, I will see if I can remove the child selector itself.

**Comment by utatti** [comment]
Now `.ps__child` itself is not needed. Thanks!

**Comment by ericdepotter** [comment]
So the scroll now works for contained children out of the box? Great, thanks!

**Comment by utatti** [comment]
Yes, it should work out of the box now. It will be released in the next (major) release.
