### ISSUE TITLE
[0.8.1] Uncaught TypeError: t.msMatchesSelector is not a function

### ISSUE THREAD

**Issue by ypanyukov** [utatti/perfect-scrollbar#682]
For some reason it calls for non elements.

Just change code in developer tools and add new lines. Chrome browser calls it text element and in DevTools it looks like this https://www.dropbox.com/s/la7x49h4degt8x7/Screenshot%202017-09-05%2019.35.54.png?dl=0

<div class="container ps ps--theme_default ps--active-x ps--active-y" data-ps-id="93b4405b-3fc1-f440-f44a-8bbaab983361">
  
    <div class="content"></div>
    
    <div class="ps__scrollbar-x-rail" style="width: 400px; left: 0px; bottom: -300px;">
        
        <div class="ps__scrollbar-x" tabindex="0" style="left: 0px; width: 125px;"></div></div><div class="ps__scrollbar-y-rail" style="top: 300px; height: 300px; right: 0px;"><div class="ps__scrollbar-y" tabindex="0" style="top: 88px; height: 88px;"></div></div></div>

Result https://www.dropbox.com/s/dobirxbi0j5g65h/Screenshot%202017-09-05%2019.34.58.png?dl=0

But if code does not contain it then it works expected

**Comment by utatti** [comment]
Resolved in the next version.

https://github.com/utatti/perfect-scrollbar/blob/next/src/lib/dom.js#L13
