### ISSUE TITLE
chrome error violations

### ISSUE THREAD

**Issue by knoxcard** [utatti/perfect-scrollbar#687]
perfect-scrollbar.jquery.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
r.bind @ perfect-scrollbar.jquery.min.js:2
o.bind @ perfect-scrollbar.jquery.min.js:2
r @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
t.fn.perfectScrollbar @ perfect-scrollbar.jquery.min.js:2
renderCart @ dispensary.js:929
addProduct @ dispensary.js:877
(anonymous) @ dispensary.js:812
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
perfect-scrollbar.jquery.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
r.bind @ perfect-scrollbar.jquery.min.js:2
o.bind @ perfect-scrollbar.jquery.min.js:2
r @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
e.exports @ perfect-scrollbar.jquery.min.js:2
(anonymous) @ perfect-scrollbar.jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
t.fn.perfectScrollbar @ perfect-scrollbar.jquery.min.js:2
renderCart @ dispensary.js:929
addProduct @ dispensary.js:877
(anonymous) @ dispensary.js:812
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
perfect-scrollbar.jquery.min.js:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment]
To remove this error and make it passive, scroll prevention should be disabled and following options should be removed.

- `wheelPropagation`
- `suppressScrollX`, `suppressScrollY`

I'm not sure it's a right decision to remove the options to use passive event. Any thought?

**Comment by utatti** [comment]
I added this to [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats) for the time being, as it's kind of inevitable in the current code base. Nonetheless, any kind of contribution will be welcomed. Please feel free to suggest a solution or upload a pull request.
