### ISSUE TITLE
_perfectScrollbar2.default is not a constructor

### ISSUE THREAD

**Issue by adsellor** [utatti/perfect-scrollbar#690]
Hi. I was trying to use the perfect scrollbar in my React project, however,  I am getting console error trying to initialize new PerfectScrollbar. Here is my code
```
const item = document.querySelector('item');
const ps = new PerfectScrollbar(item);        
```
I get this error 
```
 Uncaught (in promise) TypeError: _perfectScrollbar2.default is not a constructor
```

I did some research but couldn't find anything. 
Any help would be appreciated.

**Comment by utatti** [comment]
You may have installed perfect-scrollbar from npm? The current README is one of the next branch. Please check out master’s doc for.

 > This is documentation for the next branch. To read documentation for released versions, please visit master.

**Comment by mahdibx** [comment]
I have the same issue, there is a problem in the typings, it should not export default, the export should rather be `export = PerfectScrollbar`
