### ISSUE TITLE
Weird issue with adding/removing/adding/removing ps

### ISSUE THREAD

**Issue by madprops** [utatti/perfect-scrollbar#698]
I have a feature in my webapp where users can enable or disable custom scrollbars on the site. 

It seems that after starting/destroying/starting/destroying etc, the destroy (at least) seems to only work intermittently. As in, it works (native scrollbars appear) one time, the next one it fails.

Here's a fiddle to test it https://jsfiddle.net/ht4dg8o6/2/

**Comment by utatti** [comment]
Confirmed the bug. Will fix it!
