### ISSUE TITLE
Feature request: Autohide unless there is scrolling or hover over rail.

### ISSUE THREAD

**Issue by madprops** [utatti/perfect-scrollbar#699]
I think it would be very nice if there was an option to make the scrollbar invisible (opacity: 0) unless a user scrolls, or if the cursor is over the rail. It shouldn't appear when the scroll is triggered manually with javascript, because stuff like going to the bottom in chat applications after new messages would trigger it on every message.

**Comment by utatti** [comment]
Currently, the scrollbar is shown for 1s after it's scrolled regardless of scroll/hover. I agree that it would be better to be configured with an option.

**Comment by utatti** [comment]
It can be done by just modifying CSS. Please look into styles where `ps:hover` applies.
