### ISSUE TITLE
hello, If i want to manually change the position of the scroll bar should do? Such as scroll to top. Thank you

### ISSUE THREAD

**Issue by dingyanhe** [utatti/perfect-scrollbar#702]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

**Comment by utatti** [comment]
Tou can just set scrollTop or scrollLeft and that’s it. Please refer to README for detailed usage.
