### ISSUE TITLE
Does not scroll when selected

### ISSUE THREAD

**Issue by frontbond** [utatti/perfect-scrollbar#703]
If you select text that is larger than the container, scrolling is absent and does not select all the text

**Comment by utatti** [comment]
There was `'selection'` scroll handler but it has been removed; https://github.com/utatti/perfect-scrollbar/commit/3c5196f34003b92c2632900c4324bfc6c35a8d87.

It is basically too tricky to implement this kind of scroll emulation, and it usually provides more bugs. It's mentioned in Caveats too.

> ref: https://github.com/utatti/perfect-scrollbar/wiki/Caveats
>
> Some kind of scrolls are not emulated, such as select-and-drag, middle-click and search
