### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by katasup** [utatti/perfect-scrollbar#704]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [there](https://jsfiddle.net/g7sjrggh/1/)
- [x] Provide a page or source code where the issue can be checked

Hi! There a problem with PerfectScrollbar that when scroll is fired but not stops yet, and scrollbars destroyed, script throw an error:
```
Uncaught TypeError: Cannot read property 'classList' of null
    at perfect-scrollbar.esm.js:87
```

You can check this behaviour in fiddle, just scroll and click outside.

I use this with React, so when component is hides, i should use `destroy` method that throw an error.

**Comment by utatti** [comment]
Yes, I confirmed the problem. Will work on this.
