### ISSUE TITLE
ps-y-reach-end and ps-y-reach-start called one after another

### ISSUE THREAD

**Issue by ujtordai** [utatti/perfect-scrollbar#705]
Hi All,

I have a problem, the two events ps-y-reach-end and ps-y-reach-start called one after another.
Which is that case when can occurring this?

Thank you in advance

**Comment by utatti** [comment]
Which version do you use? If the current master is used, they will be fired on `update()` when content height is smaller than container height.

**Comment by ujtordai** [comment]
Hi,
I Use the ngx-perfect-scrollbar v 4.4.0 which useing the v 0.7.1 perfect-scrollbar.
Thank you of your reply.

**Comment by utatti** [comment]
I've checked v0.7.1 and yes, it's the same. It occurs when content height is smaller than container height.

- https://github.com/utatti/perfect-scrollbar/blob/0.7.1/src/js/plugin/update-scroll.js#L24

But in the latest version, the event won't be fired unless `update()` is called manually. Also, old versions are not maintained and I recommend upgrading to the latest one. ngx-perfect-scrollbar is not maintained by us, so please enquire in the repo.

**Comment by ujtordai** [comment]
Thank you
