### ISSUE TITLE
ReferenceError when imported in isomorphic react application

### ISSUE THREAD

**Issue by petertenhoor** [utatti/perfect-scrollbar#706]
Hi!

I am trying to implement the perfect-scrollbar package in my isomorphic react application. My react components are shared between a node server and the client. I tried to import the perfect-scrollbar package in one of my react components using ES6 import:

```import ScrollBar from "perfect-scrollbar";```

When the node server renders this component I get a ReferenceError in this file:

```node_modules\perfect-scrollbar\dist\perfect-scrollbar.common.js:31```

At this line:

``` Element.prototype.webkitMatchesSelector || ```

The error:

```ReferenceError: Element is not defined```

Does this mean that the package is not compatible with server side rendered applications?

Best regards.

Peter ten Hoor

**Comment by utatti** [comment]
Yes, it's not compatible with SSR. I would recommend disabling it on SSR.
