### ISSUE TITLE
scrollLeft no longer working in Mobile

### ISSUE THREAD

**Issue by PatMattei** [utatti/perfect-scrollbar#707]
I have a page that's been using this plugin for a few months but I just noticed that scrollLeft() functions seemed to have stopped working in Safari on iPhones and iPads (possibly other browsers/ devices as well).

I have a button that should make it scroll a certain number of pixels, which it starts to do, but then quickly jumps back to the far left, so it just creates a kind of 'shaking' effect.

http://jsfiddle.net/qpo46456/

**Comment by utatti** [comment]
`scrollLeft` is not provided by perfect-scrollbar, but by jQuery itself. Please refer to the jQuery documentation for the detail.

Also, please beware that PS dropped jQuery support in v1.0.
