### ISSUE TITLE
keep scrollY with mousewheel scrollX

### ISSUE THREAD

**Issue by glennnall** [utatti/perfect-scrollbar#708]
I set these:
  suppressScrollY: true
  useBothWheelAxes: true
so that my mousewheel scrolls X - great, that's what I want.

But I also need to be able to scroll Y with the thumb - how can I keep the Y scrollbar so I can drag up and down?

thanks

**Comment by utatti** [comment]
There's no way to do this for the time being. Do you have any suggestion how this should be configured?

**Comment by sconix** [comment]
I am bit curious about the use case. What could be a situation where you want the touch to work differently from mouse wheel when both are available? If its just that you want it to behave differently in touch device than on desktop then why not just detect if its a touch device and use different configuration.

**Comment by glennnall** [comment]
the "thumb" is the part of the scrollbar that moves - it's how utatti refers to it...
not the human thumb.
I'm just trying to utilize the y axis as well as the x axis with the mousewheel...

**Comment by sconix** [comment]
Ah ok, still wondering what could be the use case to disallow wheel but allow scrollbar to one direction. Couldn't you just leave out the suppressScrollY and capture wheel event yourself and prevent its propagation to perfect-scrollbar. This just sound something which is really rare and odd use case that having ready configuration option does not make much sense. Of course there could be suppressWheelX/Y options, but it just sounds like a rare use case.

**Comment by utatti** [comment]
Now I agree with @sconix. I cannot come up with a nice way to implement this in the current structure, and think it's not usual use case even in the native browser scroll. I'm afraid that I may not  implement this in PS, at least in a while. There may be some workaround for browser native scrolls, though.
