### ISSUE TITLE
scrollTop function not working

### ISSUE THREAD

**Issue by kirillminiaev** [utatti/perfect-scrollbar#711]
Having trouble scrolling container to the top. JSFiddle:

https://jsfiddle.net/dyvL31r6/64/

I've already tried adding an `update` function call after `ps.scrollTop = 0;` but that also doesn't do anything.

Browser: Chrome Mac 61.0.3163.100
Perfect Scroll: v.1.1.0

<hr />

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked

**Comment by sqal** [comment]
PS instance doesn't have scrollTop method. scrollTop is just native DOM property, so If you want to change scroll position just do:

```
const container = document.querySelector('#container');
container.scrollTop = 0;
// ps.update() // optional
```

https://jsfiddle.net/dyvL31r6/65/

**Comment by utatti** [comment]
@sqal's answer is the right way to do that. [How to use](https://github.com/utatti/perfect-scrollbar#how-to-use) section also describes it.
