### ISSUE TITLE
Help needed for programmatically triggering scrolling events

### ISSUE THREAD

**Issue by feanor07** [utatti/perfect-scrollbar#712]
I am one of the contributors of [ember-perfect-scroll addon](https://github.com/imanhodjaev/ember-perfect-scroll). We wrap your plugin and make it an ember component. Our latest release (v0.1.17) depends on version 0.8.1 of this plugin and I plan to update our addon to use the latest version (1.1.0).

I made necessary changes to get our addon working with latest version and it is working smoothly; however I have problem in testing. I have a test-case where I test our own component for triggering correct events (I mean ps-scroll-x, ps-y-reach-end, etc.). In order to do that I need to make your plugin trigger the corresponding event.

I used to use the following code and I was able to get events from your plugin within my component at version 0.8.1:

`$('#perfect-scroll-identifier').scrollTop(150);`
`window.Ps.update($('#perfect-scroll-identifier')[0]);`

This was forcing your plugin to trigger `ps-scroll-y` event; I am unable to do the same with latest version. However the following does not trigger the corresponding event anymore.

`$('#perfect-scroll-identifier').scrollTop(150);`
`perfectScrollbarInstance.update()'`

I have the corresponding `perfectScrollbarInstance` and calling `update` method as suggested; but this no longer triggers the desired event. Any ideas?

**Comment by utatti** [comment]
This is actually an issue. I'll look into this.
