### ISSUE TITLE
Need to clear timeouts on destroy

### ISSUE THREAD

**Issue by BONDRV** [utatti/perfect-scrollbar#714]
Function "removeScrollingClass" uses setTimeout. But if you destroing perfectScrollbar instance by using method "destroy" timeouts don't stops.
This creates error:

**Uncaught TypeError: Cannot read property 'classList' of null**

in function:
```
function removeScrollingClass(i, x) {
  scrollingClassTimeout[x] = setTimeout(
    function () { return i.element.classList.remove(cls.state.scrolling(x)); },
    i.settings.scrollingThreshold
  );
}
```

**Comment by utatti** [comment]
Duplicated: #704

It's been fixed in the latest version. Currently it checks if PS is alive.

- https://github.com/utatti/perfect-scrollbar/blob/master/dist/perfect-scrollbar.js#L93
