### ISSUE TITLE
Work with Angular 5

### ISSUE THREAD

**Issue by Insight707** [utatti/perfect-scrollbar#716]
Hello. I've updated my project to angular 5. Now, when I am trying to start a project it shows me error: 

```
ERROR in node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts(1,31): error TS2305: Module '"C:/web/
MarketplaceAdmin/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.
```

**Comment by utatti** [comment]
Hi. I’m not familiar with Angular, but according to the error message, something’s wrong in type definition in ngx-perfect-scrollbar. ngx-perfect-scrollbar is a separate project, which is not maintained by me. Please ask in its homepage.
