### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by JochenDiekenbrock** [utatti/perfect-scrollbar#718]
The class names on https://github.com/utatti/perfect-scrollbar/wiki/FAQ#how-can-i-make-the-scrollbars-always-visible should be updated to match the currently used classes:
.ps > .ps__rail-x,
.ps > .ps__rail-y {
  opacity: 0.6;
}

Sorry, I could not find out how to fork the wiki to fix this myself and create a pull request :-(

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked

**Comment by utatti** [comment]
Updated. Thanks!

**Comment by JochenDiekenbrock** [comment]
Thank you!
