### ISSUE TITLE
You can't instantiate/use 2 or more scrollbars in the same page 

### ISSUE THREAD

**Issue by MarcoBatongbacal** [utatti/perfect-scrollbar#725]
I want to have more scrollbars in one page, but it can't be done because of the id container which should be unique, I've tried also instantiating two object from two different id's but does not seem to work. Is there a way to add more scroll bar in one page?

**Comment by utatti** [comment]
It is possible, because you can just provide different id or a separate element itself. Here is an example where 2 scrollbars are initialized.

https://github.com/utatti/perfect-scrollbar/blob/master/examples/options-wheelPropagation.html

**Comment by MarcoBatongbacal** [comment]
Working on scrollbar with x axis but not working on y axis

**Comment by MarcoBatongbacal** [comment]
Sorry, it's working now thank you!
