### ISSUE TITLE
Scroll Div Horizontally With Mouse Wheel

### ISSUE THREAD

**Issue by caspermouse** [utatti/perfect-scrollbar#726]
Hello, I have one question for you. Is it possible to change some params of perfect scroll in order to be able to pass through the div horizontally with the mouse wheel.

**Comment by utatti** [comment]
Please refer to the [`useBothWheelAxes`](https://github.com/utatti/perfect-scrollbar#usebothwheelaxes-boolean) option. There is also an example for this:

- https://github.com/utatti/perfect-scrollbar/blob/master/examples/options-useBothWheelAxes.html
