### ISSUE TITLE
when child div scroll end its must be scroll parent's

### ISSUE THREAD

**Issue by chanduk040** [utatti/perfect-scrollbar#729]
@utatti, Still there is an issue with parent scroll.
In you example - http://utatti.github.io/perfect-scrollbar/ itself, once the vertical perfect scrollbar of Image container comes to its end position, it should allow the page scroll bar starts scrolling automatically. Instead it is blocking the page scroll. I think this is a serious bug.

Its been already raised by others but once again I am raising as this is not yet been resolved.

Hope you will look into this.

**Comment by konradjurk** [comment]
@chanduk040 Have you tried to enable `wheelPropagation`?

**Comment by utatti** [comment]
This will be a default behaviour in the next major version. For the discussion, please refer to #731 and #732.

**Comment by madprops** [comment]
Is this related to selecting text upwards with a mouse not moving the scrollbars to select more text?

**Comment by DzmVasileusky** [comment]
It seems that you have forgotten to update the docs.

> wheelPropagation {Boolean}
> ...
> Default: false

**Comment by AbiSubbiah** [comment]
Still i am facing above issue ie, child scroll end not triggering parent scroll. Can anyone help me on this? 

https://stackblitz.com/edit/ngx-perfect-scrollbar-dpgxdg?file=src%2Fapp%2Fapp.component.html
