### ISSUE TITLE
A way to prepend or append the scrollbar html elements

### ISSUE THREAD

**Issue by madprops** [utatti/perfect-scrollbar#733]
Hello, thank you for this great library.

Right now I'm hitting a problem where the scrollbar elements, which are appended to the container, are messing with my css/html. Specifically I can't use css's last-child correctly since the scrollbar elements are now the last childs when created.

It would be nice to have an option to set if they should be appended or prepended.

**Comment by utatti** [comment]
Currently it's somewhat difficult fix this very quickly. How about wrapping the content with another div?

**Comment by madprops** [comment]
It's not a big problem for me, it just messes temporarily some obscure feature of mine, so no worries. Maybe that wrap could work. Thanks
