### ISSUE TITLE
When we add two horizontal scrollbars they overlaps

### ISSUE THREAD

**Issue by malithmadhuranga** [utatti/perfect-scrollbar#734]
When i set perfect scrollbar horizontally in two adjacent components its overlapping. I need to add two scrollbars here. Thank You.

Where I initiate perfect scrollbar:

    componentDidMount() {
      // eslint-disable-next-line no-unused-vars
      const ps = new PerfectScrollbar('#notifications', {
        wheelSpeed: 2,
        wheelPropagation: true,
        minScrollbarLength: 20
      });

      const ss = new PerfectScrollbar('#modes', 'ps-scroll-x', {
        wheelSpeed: 1,
        wheelPropagation: true,
        minScrollbarLength: 1
      });

      const ts = new PerfectScrollbar('#presets', 'ps-scroll-x', {
        wheelSpeed: 1,
        wheelPropagation: true,
        minScrollbarLength: 1
      });
    }

The component looks like this:

    <SidebarWrapper>

      <div>

        {/* Modes */}
        <ModesAndPresets id="modes">{this.modeList()}</ModesAndPresets>
      </div>

      <Divider />

      <div>

        {/* Presets */}
        <ModesAndPresets id="presets">{this.presetList()}</ModesAndPresets>
      </div>
    </SidebarWrapper>

![screenshot from 2017-12-14 14 19 18](https://user-images.githubusercontent.com/31467012/33984736-aa21520c-e0de-11e7-9e35-af64516ff37b.png)

**Comment by utatti** [comment]
I guess this is a CSS issue. Does each container have a proper position value?

**Comment by utatti** [comment]
Closed for inactivity. Please feel free to reopen.
