### ISSUE TITLE
Prevent parent scrolling

### ISSUE THREAD

**Issue by Costegillio** [utatti/perfect-scrollbar#738]
Greetings!

For example, i have:
```
<div class='Y'>
   <div class='X'></div>
</div>
```

I initialized both of classes:
```
psY = new PerfectScrollbar(".Y", {suppressScrollX:true});
psX = new PerfectScrollbar(".X", {suppressScrollY:true});
```

When i'm scrolling in X how to prevent Y scroll?

By the way plugin is awesome, thanks!

**Comment by konradjurk** [comment]
Hi @Costegillio, I adapted the nice jsfiddle from #735 to your setup. Could you check [this out](https://jsfiddle.net/nwjbvp0q/3/) and describe what exactly is not working as expected? For me, the outer container is not scrolling.

**Comment by Costegillio** [comment]
@konradjurk, thanks for answer. Your fiddle works like a charm. 

Seems my problem is in percentage height for container, which breaks vertical scroll:
```
.container {
  height: 30%;
}
```
Is where way to use it?

[jsfiddle](https://jsfiddle.net/7q3qxsru/)

**Comment by konradjurk** [comment]
@Costegillio Oh I see, the percentage height is in relation to its parent containers (in this case `body` and `html`). Both need a height value too, otherwise it defaults to `auto`.

So 

```css
html, body {
  height: 100%;
}
```

fixes the issue for this particular case: https://jsfiddle.net/usq0fc0g/1/

**Comment by Costegillio** [comment]
@konradjurk, it's works now.

Thanks and good luck!

**Comment by OleksiiNekryshevych** [comment]
I found the solution and it works
It fixes/unfixes the scroll on the current scroll position.

```
const container= document.querySelector('./*container class*/')
let scrollbar= new PerfectScrollbar(container)

function fixScrollbar() {
        const lastScrollTop = scrollbar.lastScrollTop
	scrollbar.destroy()
	scrollbar= new PerfectScrollbar(container, {
		wheelSpeed: 0,
	})
	setTimeout(() => {
		layout.scrollTop = lastScrollTop
	})
}

function unfixScrollbar() {
	const lastScrollTop = scrollbar.lastScrollTop
	scrollbar.destroy()
	scrollbar= new PerfectScrollbar(container)
	layout.scrollTop = lastScrollTop
}
```
