### ISSUE TITLE
For some specific tags

### ISSUE THREAD

**Issue by twelvew12** [utatti/perfect-scrollbar#757]
hello, How can I use this plugin for multiple tags?

new PerfectScrollbar("#a ,#b, #c");

It is not responsive

Please help me

**Comment by utatti** [comment]
One PS instance can only have one target element, because each element usually has a separate layout. Please query elements first and then apply PS.

```js
for (const el of document.querySelectorAll('#a,#b,#c')) {
    new PerfectScrollbar(el);
}
```

**Comment by twelvew12** [comment]
Thank you
I have another problem. When will I be personalized for each individual?

const ps = new PerfectScrollbar('#a , #b , #c', {
	wheelSpeed: 0.5, 
	wheelPropagation: true,
	minScrollbarLength: 20, 
        suppressScrollY: false, 
});

**Comment by utatti** [comment]
I updated the code above.

**Comment by twelvew12** [comment]
I updated the code above.
How should I call update order now?

**Comment by utatti** [comment]
You should manually keep the list of instances.

```js
const psInstances = [];
for (const el of document.querySelectorAll('#a,#b,#c')) {
    psInstances.push(new PerfectScrollbar(el, { ... }));
}
psInstances.forEach(ps => ps.update());
```

**Comment by twelvew12** [comment]
# Thank you very much
It's ok

**Comment by twelvew12** [comment]
Hello Again
new PerfectScrollbar('body'); 
not working?
