### ISSUE TITLE
Get scroll amount?

### ISSUE THREAD

**Issue by schoening** [utatti/perfect-scrollbar#816]
I am listening for the custom events and would like to know something like the pixels or percentage of how far I have scrolled from the beginning. Is this doable at the moment or something that could be added to the custom event data perhaps?

**Comment by henken** [comment]
I have the same question.

**Comment by romanran** [comment]
It just uses the scrollLeft property on the node with scrollbar. So you can just use `yourHtmlElement.addEventListener('scroll', () => { yourHtmlElement.scrollLeft })`
